# Generated by Django 5.1.3 on 2024-12-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipes_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='cooking_process',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='number_of_servings',
            field=models.PositiveIntegerField(),
        ),
    ]
